### ISSUE TITLE
Serial port wiring

### ISSUE THREAD

**Issue by deirdreobyrne** [honupata/Altair8800_Mister#3]
Your description of how to wire a serial port is inconsistent. The diagram you give doesn't correspond with what the text says. The diagram suggests TX is Arduino_IO15, but the text says it's Arduino_IO14.

Which pin is Altair8800 transmit (i.e. USB serial cable receive) and which pin is Altair8800 receive (i.e. USB serial cable transmit)?

**Comment by honupata** [comment]
We just changed the image to reflect the text in the readme.   
   - TX SDA Arduino_IO14.
   - RX SCL Arduino_IO15.
Let us know if it is not working

Thank you

Cyril & Fred

    On Wednesday, March 27, 2019, 11:04:35 PM EDT, deirdreobyrne <notifications@github.com> wrote:  
 
 
Your description of how to wire a serial port is inconsistent. The diagram you give doesn't correspond with what the text says. The diagram suggests TX is Arduino_IO15, but the text says it's Arduino_IO14.

Which pin is Altair8800 transmit (i.e. USB serial cable receive) and which pin is Altair8800 receive (i.e. USB serial cable transmit)?

**Comment by deirdreobyrne** [comment]
When you say "TX SDA Arduino_IO14", do you mean TX from the Altair to the USB, or TX from the USB to the Altair?

**Comment by honupata** [comment]
Let me try this weekend I will get back to you on Monday.
Cyril

    On Thursday, March 28, 2019, 3:29:42 PM EDT, deirdreobyrne <notifications@github.com> wrote:  
 
 
When you say "TX SDA Arduino_IO14", do you mean TX from the Altair to the USB, or TX from the USB to the Altair?

**Comment by NEO-JAMMA** [comment]
- TX of the TTL Serial Cable Adapter -> SCL Arduino_IO15 pin of the DE-10.
  - RX of the TTL Serial Cable Adapter -> SDA Arduino_IO14 pin of the DE-10.
